### ISSUE TITLE
test failures are hard to understand

### ISSUE THREAD

**Issue by doug-wade** [redfin/react-server#41] opened 2016-02-26 03:46 UTC
In our test output, it looks like we have failures, but none are reported

```
dougwade packages/react-server ‹rename-data-triton-root-id*› » gulp test
[19:39:19] Warning: gulp version mismatch:
[19:39:19] Global gulp is 3.9.0
[19:39:19] Local gulp is 3.8.10
[19:39:20] Using gulpfile ~/code/react-server/packages/react-server/gulpfile.js
[19:39:20] Starting 'compileServer'...
[19:39:20] Starting 'compileClient'...
[19:39:21] Finished 'compileClient' after 741 ms
[19:39:21] Finished 'compileServer' after 752 ms
[19:39:21] Starting 'test'...
...........................................................(node) OutgoingMessage.flush is deprecated. Use flushHeaders instead.
...2016-02-26T03:39:25.496Z - error: [react-server.core.renderMiddleware] Error in renderPage chain message=Timed out rendering., timeWaited=196, elements=[P]
......................................................[object Object]
..2016-02-26T03:39:42.519Z - error: [react-server.core.context.Navigator] Error while handling route message=died, stack=Error: died
    at InternalServerErrorException.handleRoute (/Users/doug.wade/code/react-server/packages/react-server/target/server/__tests__/integration/internalServerError/pages/InternalServerErrorException.js:26:10)
    at /Users/doug.wade/code/react-server/packages/react-server/target/server/util/PageUtil.js:358:25
    at /Users/doug.wade/code/react-server/packages/react-server/target/server/util/PageUtil.js:350:15
    at /Users/doug.wade/code/react-server/packages/react-server/node_modules/continuation-local-storage/context.js:74:17
    at _fulfilled (/Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:796:13)
    at /Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:857:14
    at runSingle (/Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:137:13)
    at flush (/Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:125:13)
    at /Users/doug.wade/code/react-server/packages/react-server/node_modules/async-listener/glue.js:188:31
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)
[object Object]
.2016-02-26T03:39:42.524Z - error: [react-server.core.context.Navigator] Error while handling route rejected
[object Object]
..........................................................

177 specs, 0 failures
Finished in 0 seconds
[19:39:59] Finished 'test' after 39 s
```

**Comment by roblg** [comment] 2016-02-26 05:13
I think these are error conditions that we're intentionally inducing, so the logging is scary but the output is correct. We should figure out how to silence the logger.

> internalServerError/pages/InternalServerErrorException.js

**Comment by gigabo** [comment] 2016-02-26 17:19
I think this is a dupe of #26.

**Closed by gigabo** 2016-02-26 17:19 UTC

**Comment by doug-wade** [comment] 2016-02-27 01:38
The number of specs seems to change too?

```
dougwade packages/react-server ‹better-readme› » gulp build && gulp test
[17:35:18] Warning: gulp version mismatch:
[17:35:18] Global gulp is 3.9.0
[17:35:18] Local gulp is 3.8.10
[17:35:19] Using gulpfile ~/code/react-server/packages/react-server/gulpfile.js
[17:35:19] Starting 'compileClient'...
[17:35:19] Starting 'compileServer'...
[17:35:20] Finished 'compileClient' after 951 ms
[17:35:20] Finished 'compileServer' after 941 ms
[17:35:20] Starting 'compile'...
[17:35:20] Finished 'compile' after 14 μs
[17:35:20] Starting 'build'...
[17:35:20] Finished 'build' after 4.85 μs
[17:35:20] Warning: gulp version mismatch:
[17:35:20] Global gulp is 3.9.0
[17:35:20] Local gulp is 3.8.10
[17:35:21] Using gulpfile ~/code/react-server/packages/react-server/gulpfile.js
[17:35:21] Starting 'compileServer'...
[17:35:21] Starting 'compileClient'...
[17:35:21] Finished 'compileClient' after 102 ms
[17:35:21] Finished 'compileServer' after 113 ms
[17:35:21] Starting 'test'...
.................................(node) OutgoingMessage.flush is deprecated. Use flushHeaders instead.
...2016-02-27T01:35:26.302Z - error: [react-server.core.renderMiddleware] Error in renderPage chain message=Timed out rendering., timeWaited=196, elements=[P]
...[object Object]
..2016-02-27T01:35:29.287Z - error: [react-server.core.context.Navigator] Error while handling route message=died, stack=Error: died
    at InternalServerErrorException.handleRoute (/Users/doug.wade/code/react-server/packages/react-server/target/server/__tests__/integration/internalServerError/pages/InternalServerErrorException.js:26:10)
    at /Users/doug.wade/code/react-server/packages/react-server/target/server/util/PageUtil.js:358:25
    at /Users/doug.wade/code/react-server/packages/react-server/target/server/util/PageUtil.js:350:15
    at /Users/doug.wade/code/react-server/packages/react-server/node_modules/continuation-local-storage/context.js:74:17
    at _fulfilled (/Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:796:13)
    at /Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:857:14
    at runSingle (/Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:137:13)
    at flush (/Users/doug.wade/code/react-server/packages/react-server/node_modules/q/q.js:125:13)
    at /Users/doug.wade/code/react-server/packages/react-server/node_modules/async-listener/glue.js:188:31
    at nextTickCallbackWith0Args (node.js:415:9)
    at process._tickCallback (node.js:344:13)
[object Object]
.2016-02-27T01:35:29.293Z - error: [react-server.core.context.Navigator] Error while handling route rejected
[object Object]
.............................................................................................................

151 specs, 0 failures
Finished in 0 seconds
[17:36:00] Finished 'test' after 39 s
```
