### ISSUE TITLE
Use tree shaking

### ISSUE THREAD

**Issue by doug-wade** [redfin/react-server#237] opened 2016-05-31 20:25 UTC
This could in theory reduce the size of the initial bundle. Webpack 2 is not out of beta, yet, though, so we'd have to migrate to [rollup](https://github.com/rollup/rollup).

Migrated from #50

**Comment by doug-wade** [comment] 2016-05-31 20:37
From @kcjonson 

>>> Tree shaking is awesome but good linting goes a long way for blocking unused imports, especially if everything is on ES6 syntax 😉
Seems like we should do this before we look at RootElements having their own CSS. Highly theoretical but we could use the new System.import syntax to write CSS dependencies in as RootElements are encountered, or even resolved.
If we're planning on upgrading to webpack 2, seems like we should do it first since there were "major changes" to the resolver which might effect other work. However, its in beta so are we ok with the following items being held up by it?

**Comment by doug-wade** [comment] 2016-08-16 00:27
More evidence in favor of rollup instead of webpack https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/

**Comment by drewpc** [comment] 2017-01-09 17:45
Webpack 2 is out of beta now...maybe worth taking a look at migrating from Webpack 1 to Webpack 2 and using the tree shaking stuff there: https://medium.com/modus-create-front-end-development/webpack-2-tree-shaking-configuration-9f1de90f3233

**Comment by roblg** [comment] 2017-01-10 17:57
FYI, I started this upgrade for Redfin's code internally, and one issue that I ran into that I haven't figured out yet is that the ExtractTextPlugin is still busted in watch mode, and the little hack we use in `react-server-cli` to "subclass" ETWP and make in non-cacheable didn't seem to work to fix it this time. :(

**Comment by karlhorky** [comment] 2017-01-11 18:19
webpack 2 has released a final release candidate before shipping the final version 2: https://twitter.com/TheLarkInn/status/819215334590783489

**Comment by doug-wade** [comment] 2017-01-11 21:42
> Maybe even today 😏

Woah.  Let's land #809 so that @drewpc doesn't have to entirely rewrite that _super awesome_ pr, and then jump on this.

**Comment by drewpc** [comment] 2017-01-11 22:10
@doug-wade thanks for the shout out!  Unfortunately....that super awesome PR was kinda thrown out.  I'll need to rewrite it anyway.  There's a number of architecture decisions that need to be made first, including when/if to move to Webpack 2.

**Comment by roblg** [comment] 2017-01-11 23:24
Oh! One other thing I just remembered about webpack 2 that we should be careful about: I can't find the exact numbers, but it slowed down our internal 90s build by >1min. For now, it's just an FYI, but I'd hate to force all users to suffer through perf problems because of us upgrading from webpack 1-2.

**Comment by karlhorky** [comment] 2017-01-12 07:36
cc @jhnns regarding v2 performance problems

**Comment by jhnns** [comment] 2017-01-12 10:14
I haven't heard of such a big increase in build time, but it can be. We still don't have big test projects to check performance regressions in build times 😢 

One thing I wanted to point out is that tree shaking will currently have little effect because many libs are still published in CommonJS. So, this optimization will still take some time to be effective.

**Comment by drewpc** [comment] 2019-04-30 18:28
This is addressed in #1003

**Closed by drewpc** 2019-04-30 18:28 UTC
Labels: enhancement
