### ISSUE TITLE
Move express server to react-server

### ISSUE THREAD

**Issue by jhnns** [redfin/react-server#796] opened 2017-01-04 18:41 UTC
Following up #794 

---

The actual express server is initialized inside the [`start` module of `react-server-cli`](https://github.com/redfin/react-server/blob/676e8532a4f07cd6855f161b5dfe3599e6c62d40/packages/react-server-cli/src/commands/start.js). Since I don't think that the CLI should be concerned with runtime configuration, especially middleware configuration, I would move this to `react-server/bin`. This would nicely align with a typical express app where the actual server is placed under `bin`. It would also underline the separation between `react-server-cli` (build stuff) and `react-server` (runtime).

If you're against this option, we should still move the actual express server into a dedicated file. This way we can easily spawn a separate process.

**Comment by doug-wade** [comment] 2017-01-04 18:47
I think I might be opposed to this one; at least, it is at disharmony with #547, #536 and #247.  Personally, I'd prefer to allow users to have a connect/express/koa/hapi/http-server/whatever instance and register react-server as a middleware on that server.  In practice, we might not be able to support everything, but it seems strange that a _requirement_ of using react-server is that you have to have a separate api server; seems like it should at least be an option to have a single server have both your api and your front-end on it.

**Comment by jhnns** [comment] 2017-01-04 18:51
> I'd prefer to allow users to have a connect/express/koa/hapi/http-server/whatever instance and register react-server as a middleware on that server

Fair enough.

For me it's surprising that a CLI tool hosts the actual application server. We could also move this to a different package, like `react-server-express`.

**Comment by roblg** [comment] 2017-01-04 18:56
> We could also move this to a different package, like `react-server-express`.

I think I'm in favor of that approach. I also agree that having a CLI too that embeds the server in it is confusing, and I think it makes it more difficult to do other things we've discussed (e.g., have separate processes for server and client webpack builds).

**Comment by drewpc** [comment] 2017-01-09 17:27
Isn't this a duplicate of #33? Maybe the name of that issue needs to be changed to something more descriptive.

**Comment by jhnns** [comment] 2017-01-10 08:35
> Isn't this a duplicate of #33

Seems so, yes.

**Closed** 2017-01-16 16:41 UTC
