### ISSUE TITLE
react-server vs. react-flexbox-grid

### ISSUE THREAD

**Issue by curio77** [redfin/react-server#802] opened 2017-01-04 20:52 UTC
This is sort of a cross-post of an [issue](/roylee0704/react-flexbox-grid/issues/84) I opened with [react-flexbox-grid](https://roylee0704.github.io/react-flexbox-grid/) because I'm not sure which of the two is the culprit.

I've been toying with `react-server` in conjunction with `react-flexbox-grid` and got the latter to work in principle.

However, I now get checksum mismatch warnings between the server- and client-rendered HTML for `react-flexbox-grid` components, to the tune of this (for a `<Row/>`):

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
(client) tid="1"><div class="flexboxgrid__row___c
(server) tid="1"><div class="" data-reactid="2">
```

As can be seen, while (mangled) class names are (correctly) inserted on the client side, the `class` attribute remains empty on the server side. Besides negating much of the advantages of SSR, this has the effect that the desired layout is only established split seconds after the page has been loaded and content has been rendered, which is rather irritating for the user.

Has anybody else used `react-flexbox-grid` with `react-server`, and if so, without this issue? In that case, what's your `webpack` config?

For me, adding

```javascript
    {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract("style", "css?modules&sourceMap&localIdentName=[name]__[local]___[hash:base64:5]"),
    }
```

to `module.loaders` made things work in principle (solving an apparently common issue where `flexboxgrid`'s CSS is interpreted as JS per default), but the issue described remains. :-(

**Comment by curio77** [comment] 2017-01-05 13:21
Well, in retrospect, this seems related to #689.

**Comment by jhnns** [comment] 2017-01-12 11:13
Yes, that's a duplicate of #689

**Closed** 2017-01-12 11:48 UTC
